### ISSUE TITLE
todos after summit

### ISSUE THREAD

**Issue by manuel3108** [sveltejs/cli#60]
**Highest priority**

Finalize which adders can be talked about in video

- [x] auth (https://github.com/sveltejs/cli/issues/68)
- [x] paraglide (https://github.com/sveltejs/cli/pull/67)
- [x] cleanup adder selection screen (https://github.com/sveltejs/cli/pull/112)

**Polish**

- [x] paraglide formatting. why no indentation? #104 
- [x] prompt before installing deps (https://github.com/sveltejs/cli/issues/128)
- [x] tailwind plugins (https://github.com/sveltejs/cli/issues/27)
- [x] get access to all relevant `npm` packages / org, namely `sv` and `@sveltejs`
- [x] prepare changeset #70 
- [x] doc/readme updates (https://github.com/sveltejs/cli/pull/93)

**Shortly post-launch**

- [x] open repository
- [ ] recast formatting (https://github.com/sveltejs/cli/issues/118)
- [x] issue / pr templates?
- [x] include script to update kit template for stackblitz in ci (https://github.com/sveltejs/cli/pull/147)
- [x] docs to recommend sv instead of create-svelte and svelte-add
- [x] deprecate `create-svelte` and/or have it print a message telling users about `sv`. maybe make it an alias for `sv create`? otherwise, delete `create-svelte` code from `kit` repo
- [x] move / duplicate [relevant issues](https://github.com/svelte-add/svelte-add/issues?q=is%3Aopen+is%3Aissue+-label%3A%22make+a+new+adder%22+-label%3Asolved-by-rewrite) from `svelte-add`
- [x] archive `svelte-add`
- [x] drop `svelte-add` website
- [x] add package provenance back https://github.com/sveltejs/cli/pull/110 (#173)
- [x] use full `svelte@5` packages for created templates (instead of rc) #174

**Later after summit**

- [ ] should we add the cli repo to ecosystem-ci?
- [x] docs (maybe omnisite, or at least some readmes) #71 
- [x] cleanup API and open to community adders (moved to #184)
	- [x] remove `workspace:*` references in community adder template (moved to #184)
